# Generated by Django 3.0.2 on 2021-05-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=10)),
                ('Last_name', models.CharField(max_length=15)),
                ('Salario', models.FloatField()),
                ('data_nascimento', models.DateField(verbose_name='Data do Evento')),
                ('cidade', models.CharField(max_length=10)),
                ('Aprovacao', models.BooleanField()),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
    ]
